import Head from 'next/head';

export default function Home() {

  return (
    <div className='w-full min-h-screen flex items-center justify-center'>
      <Head>
        <title>PillCare</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
    </div>

  );
}
